### PR TITLE
Add MIDI file writer

### PR DESCRIPTION
**Pull request by OlivierNicole**
For my own needs, I wrote a MIDI writer in complement of your MIDI parser.

I open this as a draft for two reasons:

- I did not yet implement the serialization of SysEx events
- MIDI writing does not seem very relevant for Llama. But maybe the parser and writer could be extracted into a standalone library?

### CODE REVIEW

**Comment by OlivierNicole** [comment]
I have not performed extensive testing, but I checked it by parsing a MIDI of Bach’s BWV 772, writing it to another file, and checking that the two files are byte-wise identical.

**Comment by OlivierNicole** [comment]
I implemented the missing events in the MIDI writer.

So are you considering including this into Llama? Or is it not relevant?

**Comment by gridbugs** [comment]
Hey, yep I'm planning to merge this tomorrow as part of the hacking days.

**Comment by gridbugs** [comment]
Thanks so much for this change :)

**Pull request merged**
